### Загрузка
```{r include=TRUE, echo=TRUE, warning=FALSE, message=FALSE}
# Загрузка
library(tidyverse)
library(knitr)

Crop_Soil <- read_csv("Crop_Soil.csv")
tibble(Crop_Soil)
```
### Очистка и преобразование

```{r include=TRUE, echo=TRUE,warning=FALSE, message=FALSE}

is_na_search <- colSums(is.na(Crop_Soil)) 
kable(is_na_search)

```
### Проверка на нормальность распределения данных
```{r include=TRUE, echo=TRUE,warning=FALSE, message=FALSE}

normality_results <- Crop_Soil %>%
  group_by(`Crop Type`) %>%  
  summarise(
    shapiro_p_value_Temparature = shapiro.test(Temparature)$p.value,  
    shapiro_p_value_Humidity = shapiro.test(Humidity)$p.value,        
    shapiro_p_value_Moisture = shapiro.test(Moisture)$p.value,        
    shapiro_p_value_Nitrogen = shapiro.test(Nitrogen)$p.value,        
    shapiro_p_value_Potassium = shapiro.test(Potassium)$p.value,     
    shapiro_p_value_Phosphorous = shapiro.test(Phosphorous)$p.value  
  )
kable(normality_results)

```
### Тест Крускала-Уоллиса

```{r include=TRUE, echo=TRUE,warning=FALSE, message=FALSE}

# Создание таблицы результатов
results <- tibble(
  Variable = character(),
  Chi_Squared = numeric(),
  DF = numeric(),
  P_Value = numeric()
)

# Функция для добавления результатов
add_result <- function(results, variable, test_result) {
  results <- bind_rows(results, tibble(
    Variable = variable,
    Chi_Squared = test_result$statistic,
    DF = test_result$parameter,
    P_Value = test_result$p.value
  ))
  return(results)
}

# Тесты Крускала-Уоллиса, с добавлением результатов в таблицу
results <- add_result(results, "Temparature", kruskal.test(Temparature ~ `Crop Type`, data = Crop_Soil))
results <- add_result(results, "Humidity", kruskal.test(Humidity ~ `Crop Type`, data = Crop_Soil))
results <- add_result(results, "Moisture", kruskal.test(Moisture ~ `Crop Type`, data = Crop_Soil))
results <- add_result(results, "Nitrogen", kruskal.test(Nitrogen ~ `Crop Type`, data = Crop_Soil))
results <- add_result(results, "Potassium", kruskal.test(Potassium ~ `Crop Type`, data = Crop_Soil))
results <- add_result(results, "Phosphorous", kruskal.test(Phosphorous ~ `Crop Type`, data = Crop_Soil))

kable(results)

# Построение визуализации сравнение Крускала-Уоллиса (p-value) 
ggplot(results, aes(x = Variable, y = P_Value, fill = Variable)) +
  geom_col(position = "dodge") +
  geom_text(aes(label = round(P_Value, 3), vjust = -0.5)) +
  labs(title = "Значение p-value (Potassium) статистически значимо",
       x = "Тип сельхоз.культуры",
       y = "Уровень значимости") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


### Тест Манна Уитни 

```{r include=TRUE, echo=TRUE,warning=FALSE, message=FALSE}

# Тест Манна Уитни - для попарного сравнения 
pairwise_test <- pairwise.wilcox.test(Crop_Soil$Potassium,
                 Crop_Soil$`Crop Type`, p.adjust.method = "bonferroni")

# Преобразование результатов в таблицу
table_p <- as.data.frame(pairwise_test$p.value) %>% 
rownames_to_column(var = "Group_1") %>% 
pivot_longer(cols = -Group_1, names_to = "Group_2", values_to ="p_value")


# Построение визуализации попарного сравнения
ggplot(table_p, aes(x = Group_1, y = Group_2, fill = p_value)) +
  geom_tile(color = "white") +
  scale_fill_gradient(low = "#FF0000", high = "#6666FF") +
  geom_text(aes(label = round(p_value, 2)), color = "black", size = 4) +
  labs(title = "Незначительное различия между 4 группами",
       x = "Тип сельхоз.культуры (Группа 1)",
       y = "Тип сельхоз.культуры (Группа 2)") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```
