### Загрузка и просмотр
```{r, include = TRUE, echo = TRUE}

# Загрузка библиотек
library(tidyverse)
library(modelr)
library(readr)
library(knitr)

# Загрузка данных
s_c_p <- read_csv("s_c_p.csv")

# Просмотр
head_s <- head(s_c_p) 
kable(head_s)

```
### Очистка и преобразование


```{r, include = TRUE, echo = TRUE}
search_na <- s_c_p %>% 
  summarise(
    across(everything(), ~sum(is.na(.)))
  ) 
kable(search_na)

# Разделение на возрастные категории и кругпировка и вывод подсчет средних показателей
Age_g <- s_c_p %>%  
  mutate(
    Age_group = case_when(
      Age >= 18 & Age <= 29 ~ "18-29",
      Age >= 30 & Age <= 39 ~ "30-39",
      Age >= 40 & Age <= 49 ~ "40-49",
      Age >= 50 & Age <= 59 ~ "50-59",
      TRUE ~ "Other"  
    )
  ) %>% 
  group_by(Age_group) %>%  
  summarise(
    stress_level = mean(`Stress Level`),  
    mean_exercise = mean(`Exercise (mins/day)`),
    mean_caffeine = mean(`Caffeine Intake (mg)`),
    mean_sleep_total = mean(`Total Sleep Hours`),
    mean_screen_time = mean(`Screen Time Before Bed (mins)`),
    mean_work_time =  mean(`Work Hours (hrs/day)`)
  ) 
kable(Age_g)
```
### Статистика


```{r, include = TRUE, echo = TRUE}
# Статистика по каждой переменной
stat_1 <- s_c_p %>%
  select(3:15) %>% 
  summary()
kable(stat_1)
```
#### Проверка гипотизы: Есть ли значимые различия между 2 группами

```{r, include = TRUE, echo = TRUE}

# Разделение данных на группы
gr_t_sleep_female <- s_c_p %>% 
  select(Gender, `Total Sleep Hours`) %>% 
  filter(Gender == "Female") 

gr_t_sleep_male <- s_c_p %>% 
  select(Gender, `Total Sleep Hours`) %>% 
  filter(Gender == "Male") 

# Обьединение групп
combined_data <- rbind(
  data.frame(Gender = "Female", `Total_Sleep_Hours` = 
               gr_t_sleep_female$`Total Sleep Hours`),
  data.frame(Gender = "Male", `Total_Sleep_Hours` =
               gr_t_sleep_male$`Total Sleep Hours`)
)

# Проверка данных на нормальность для женщин
shapiro.test(gr_t_sleep_female$`Total Sleep Hours`)

# Построение гистограммы для проверки на нормальность распределения данных
ggplot(data = gr_t_sleep_female, aes(x = `Total Sleep Hours`)) +
  geom_histogram(binwidth = 0.2, fill = "skyblue", color = "black", alpha = 0.7) +
  geom_density(aes(y = after_stat(density) * 0.2 * nrow(gr_t_sleep_female)), 
               color = "red", linewidth = 1) +
  labs(title = "Распределение общего количества часов сна у женщин",
       x = "Total Sleep Hours",
       y = "Frequency") +
  theme_minimal()

# Проверка данных на нормальность для мужчин
shapiro.test(gr_t_sleep_male$`Total Sleep Hours`)

# Построение гистограммы для проверки на нормальность распределения данных
ggplot(data = gr_t_sleep_male, aes(x = `Total Sleep Hours`)) +
  geom_histogram(binwidth = 0.2, fill = "skyblue", color = "black", alpha = 0.7) +
  geom_density(aes(y = after_stat(count) * 0.2), color = "red", linewidth = 1) +
  labs(title = "Распределение общего количества часов сна у женщин",
       x = "Total Sleep Hours",
       y = "Frequency") +
  theme_minimal()

# Тест Манна-Уитни
wilcox.test(gr_t_sleep_female$`Total Sleep Hours`,
            gr_t_sleep_male$`Total Sleep Hours`)

# Построение boxplot - ящик с усами
ggplot(data = combined_data, 
       aes(x = Gender, 
           y = `Total_Sleep_Hours`,
           fill = Gender)) +
  geom_boxplot(width = 0.5) +
  labs(title = "Сравнение общего количества часов сна по полу",
       x = "Пол",
       y = "Время сна",
       fill = "Пол") +
  theme_minimal()
```

