### Загрузка и просмотр
```{r, include = TRUE, echo = TRUE}

# Загрузка библиотек
library(tidyverse)
library(modelr)
library(readr)
library(knitr)

# Загрузка данных
s_c_p <- read_csv("s_c_p.csv")

# Просмотр
head_s <- head(s_c_p) 
kable(head_s)

```
### Очистка и преобразование


```{r, include = TRUE, echo = TRUE}
search_na <- s_c_p %>% 
  summarise(
    across(everything(), ~sum(is.na(.)))
  ) 
kable(search_na)

# Разделение на возрастные категории и кругпировка и вывод подсчет средних показателей
Age_g <- s_c_p %>%  
  mutate(
    Age_group = case_when(
      Age >= 18 & Age <= 29 ~ "18-29",
      Age >= 30 & Age <= 39 ~ "30-39",
      Age >= 40 & Age <= 49 ~ "40-49",
      Age >= 50 & Age <= 59 ~ "50-59",
      TRUE ~ "Other"  
    )
  ) %>% 
  group_by(Age_group) %>%  
  summarise(
    stress_level = mean(`Stress Level`),  
    mean_exercise = mean(`Exercise (mins/day)`),
    mean_caffeine = mean(`Caffeine Intake (mg)`),
    mean_sleep_total = mean(`Total Sleep Hours`),
    mean_screen_time = mean(`Screen Time Before Bed (mins)`),
    mean_work_time =  mean(`Work Hours (hrs/day)`)
  ) 
kable(Age_g)
```
### Статистика


```{r, include = TRUE, echo = TRUE}
# Статистика по каждой переменной
stat_1 <- s_c_p %>%
  select(3:15) %>% 
  summary()
kable(stat_1)
```
### Уровень стресса и количество потребляемого кофеина


```{r, include = TRUE, echo = TRUE, fig.width = 5, fig.height = 4, out.width = "50%",fig.show='hold'}

# График для среднего уровня стресса
ggplot(data = Age_g, aes(x = Age_group, 
                         y = stress_level, fill = Age_group)) +
  geom_bar(stat = "identity", position = "dodge", 
           width = 0.5, show.legend = FALSE) +
  geom_text(aes(label = round(stress_level, 1)), 
            vjust = -0.5, 
            size = 3) +
  labs(x = "Возрастные категории",
       y = "Уровень стресса",
       fill = "Возрастные 
  категории") +
  theme_classic() +
  scale_fill_brewer(palette = "Set2") 

# График для среднего уровня употребляемого кофеина (мг)
ggplot(data = Age_g, aes(x = Age_group, y = mean_caffeine, 
                         fill =  Age_group)) +
  geom_bar(stat = "identity", position = "dodge", width = 0.6) +
  geom_text(aes(label = round(mean_caffeine, 1)), 
            vjust = -0.5, 
            size = 3) +
  labs(x = "Возрастные категории",
       y = "Количество употребляемого кофеина (мг)",
       fill = "Возрастные 
  категории") +
  theme_classic() +
  scale_fill_brewer(palette = "Set2")

```

### Среднее время сна, использования телефона


```{r, include = TRUE, echo = TRUE, fig.width = 5, fig.height = 4, out.width = "50%",fig.show='hold'}

# График для среднего количество часов сна
ggplot(data = Age_g, aes(x = Age_group, y = mean_sleep_total, 
                         fill = Age_group)) +
  geom_bar(stat = "identity", position = "dodge", 
           width = 0.5, show.legend = FALSE) +
  geom_text(aes(label = round(mean_sleep_total, 1)),
                vjust = -0.5,
                size = 3) +
  labs(x = "Возрастные категории",
       y = "Количество часов сна",
       fill = "Возрастные 
  категории") +
  theme_classic() +
  scale_fill_brewer(palette = "Set2")

# График для среднего времени проведенного за телефоном в (минутах)
ggplot(data = Age_g, aes(x = Age_group, y = mean_screen_time, 
                         fill = Age_group)) +
  geom_bar(stat = "identity", position = "dodge", width = 0.6) +
  geom_text(aes(label = round(mean_screen_time, 1)),
                vjust = -0.5,
                size = 3) +
  labs(x = "Возрастные категории",
       y = "Время проведенное за телефоном, перед сном",
       fill = "Возрастные 
  категории") +
  theme_classic() +
  scale_fill_brewer(palette = "Set2")
```

### Количество часов работы и упражнений в день


```{r, include = TRUE, echo = TRUE, fig.width = 5, fig.height = 4, out.width = "50%", fig.show='hold'}

# График для среднего времени упражнений в (минутах)
ggplot(data = Age_g, aes(x = Age_group, y = mean_exercise, fill = Age_group)) +
  geom_bar(stat = "identity", position = "dodge", 
           width = 0.5, show.legend = FALSE) +
  geom_text(aes(label = round(mean_exercise, 1)),
            vjust = -0.5,
            size = 3) +
  labs(x = "Возрастные категории",
       y = "Среднее время упражнений (мин/день)",
       fill = "Возрастные категории"  
  ) +
  theme_classic() +
  scale_fill_brewer(palette = "Set2")

# График для среднего времени работы в (часах)
ggplot(data = Age_g, aes(x = Age_group, y = mean_work_time, fill = Age_group)) +
  geom_bar(stat = "identity", position = "dodge", width = 0.6) +
  geom_text(aes(label = round(mean_work_time, 1)),
            vjust = -0.5,
            size = 3) +
  labs(
    x = "Возрастные категории",
    y = "Среднее время работы (часов/день)",  
    fill = "Возрастные 
  категории" 
  ) +
  theme_classic() +
  scale_fill_brewer(palette = "Set2")
```